### ISSUE TITLE
ImportError without optional dependencies

### ISSUE THREAD

**Issue by RazerM** [SergeyPirogov/testcontainers-python#13]
After #8, `from testcontainers import PostgresContainer` fails because `__init__.py` imports the selenium submodule.

If you want to keep the top level imports the submodules will need to catch `ImportError` and set the imported names as `None`. Then in the classes that use them check if the imported names are None and raise an exception about the optional dependencies.

**Comment by SergeyPirogov** [comment]
@RazerM could you provide PR to fix this?

**Comment by DStape** [comment]
I'm also seeing a similar issue when attempting to use the MySqlContainer, but instead of ```ImportError``` I'm seeing a ```ModuleNotFoundError``` for selenium.

**Comment by DStape** [comment]
I think #17 will fix the ```ModuleNotFoundError``` as the imports in ```testcontainers/__init__.py``` have been removed which is what seemed to be causing the problem.

**Comment by SergeyPirogov** [comment]
Thank's for your contribution

**Comment by DStape** [comment]
No probs, would it be possible to make a new release with all the latest changes? That way I won't need to install all the extra dependencies I have no interest in (selenium, etc). Thanks.

**Comment by SergeyPirogov** [comment]
Will do it this weekend.

**Comment by DStape** [comment]
Sounds good, thanks!

**Comment by SergeyPirogov** [comment]
v2.2 has been released to PYPI.

**Comment by DStape** [comment]
Thanks @SergeyPirogov.
