### ISSUE TITLE
PyPI link is broken

### ISSUE THREAD

**Issue by RazerM** [SergeyPirogov/testcontainers-python#6]
The home page link on PyPI points to https://github.com/SergeyPirogov/python-testcontainers

**Comment by SergeyPirogov** [comment]
@RazerM Yes, where is a mistake?

**Comment by RazerM** [comment]
Sorry I pasted the wrong link, I updated my comment

**Comment by SergeyPirogov** [comment]
it's because of wrong link in setup.py https://github.com/SergeyPirogov/testcontainers-python/blob/d44d1bc2bf054aff7114fe6d89db11e453149485/setup.py#L26
