### ISSUE TITLE
Use extras for optional dependencies

### ISSUE THREAD

**Issue by RazerM** [SergeyPirogov/testcontainers-python#7]
Currently, selenium, pymysql, and psycopg2 are all installed regardless of what I need.

Extras should be used like [sqlalchemy does](https://github.com/zzzeek/sqlalchemy/blob/2c280791886756422a8103769cf131b0fe292ffe/setup.py#L156-L165).

That way, I can have `testcontainers[postgresql,mysql]` as a dependency if that's all I need.

I can submit a PR if you like.

**Comment by RazerM** [comment]
Actually, is there a reason that `DbContainer._connect` is called at all? Is it just to check the database is reachable?

It might make more sense to remove sqlalchemy, psycopg2, and pymysql dependencies (well, change to test dependencies) from testcontainers.

**Comment by SergeyPirogov** [comment]
@RazerM feel free to send a PR to fix this
